### ISSUE TITLE
Timestamp is wrong

### ISSUE THREAD

**Issue by tegacodes** [alexnathanson/solar-protocol#4]
My pi is currently the active server but on the website is publishing the wrong time ( 16:41:33 ) when it is 10.27 am.
The time setting on the pi are correct, I had thought this time stamp was coming from datetime of the pi, as requested in the createHTML script? That is gives me the correct time when I run it directly on the pi so I'm not sure how this error is happening.

**Comment by tegacodes** [comment]
Update: seems that my createHTML script is not running regularly. Need to check why it is not running every 15min

**Comment by jedahan** [comment]
closing as stale - we have instructions on setting timezone
