### ISSUE TITLE
How to publish a website?

### ISSUE THREAD

**Issue by da5nsy** [alexnathanson/solar-protocol#68]
`http://solarprotocol.net/guide-creatingasite.html` says:

> You can also publish a website on the Solar Protocol platform, even if you aren’t stewarding a server.

but it doesn't seem to have any further information.
How would one apply to have data hosted on the Solar Protocol platform?

**Comment by alexnathanson** [comment]
Hi! Thanks for your interest! We're not accepting applications for hosted content at this time, but we hope to again in the future.
